version: '3.8'

services:
  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_SEARCH_API_KEY: ${AZURE_SEARCH_API_KEY}
      AZURE_SEARCH_ENDPOINT: ${AZURE_SEARCH_ENDPOINT}
      AZURE_SEARCH_INDEX_NAME: ${AZURE_SEARCH_INDEX_NAME}
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # 배포 환경에서는 실제 proxy-server URL 사용
        VITE_API_BASE_URL: https://dopaminesun-server-dycxgacfcmbcc2ec.eastus2-01.azurewebsites.net
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: https://dopaminesun-server-dycxgacfcmbcc2ec.eastus2-01.azurewebsites.net
    depends_on:
      - proxy-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge