version: '3.8'

services:
  proxy-server:
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_SEARCH_API_KEY: ${AZURE_SEARCH_API_KEY}
      AZURE_SEARCH_ENDPOINT: ${AZURE_SEARCH_ENDPOINT}
      AZURE_SEARCH_INDEX_NAME: ${AZURE_SEARCH_INDEX_NAME}
    networks:
      - app-network

  frontend:
    image: dopaminesun.azurecr.io/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: http://proxy-server:3001
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: http://proxy-server:3001
    depends_on:
      - proxy-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
